import 'package:mongo_dart/mongo_dart.dart';

class User {
  final ObjectId id;
  final String email;
  final String? name;
  final String hashedPassword;

  User({
    required this.id,
    required this.email,
    this.name,
    required this.hashedPassword,
  });

  /// from MongoDB map
  factory User.fromMap(Map<String, dynamic> map) => User(
    id: map['_id'] as ObjectId,
    email: map['email'] as String,
    name: map['name'] as String?,
    hashedPassword: map['hashedPassword'] as String,
  );

  /// to MongoDB map (id generated by Mongo)
  Map<String, dynamic> toMap() => <String, dynamic>{
    'email': email,
    if (name != null) 'name': name,
    'hashedPassword': hashedPassword,
  };
}
